default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: summer_reading-development
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: summer_reading-test
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>



